### ISSUE TITLE
Can't Proceed Past Jira Token Type, Enter a Number:

### ISSUE THREAD

**Issue by otherfutures** [mk-5/fjira#103]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Terminal: Powershell
 - Architecture: x86
 - Fjira version: 1.2.3

**Describe the bug**
Trying input any answer to answer Jira Token Type results in a response of e.g. '1\r is not a valid input. Answer by a number.' when trying to set up Fjira for the first time

**To Reproduce**
3. See error

**Expected behavior**

**Additional notes**
Everything that could help to explain your problem. Ex. Screenshots

**Comment by mk-5** [comment]
@otherfutures I will look on it right away

**Comment by mk-5** [comment]
okay - I can reproduce it, fix is on a way

**Comment by otherfutures** [comment]
Choco is also how I downloaded it (forgot to mention it in the post above). It seemed to work fine on my machine though(?)

**Comment by mk-5** [comment]
> Choco is also how I downloaded it (forgot to mention it in the post above). It seemed to work fine on my machine though(?)

mhm okay - then it could be some problem with my Windows machine

**Comment by mk-5** [comment]
@otherfutures  as a "walkaround" for now - you can just create the configuration file manually. 

File should be located under your user home directory, `~/.fjira/fjira.yaml`

The configuration file structure goes like this:

```
current: default
workspaces:
    default:
        jiraRestUrl: https://something.atlassian.net
        jiraToken: $TOKEN_HERE
        jiraUsername: your@email.com
        jiraTokenType: api token
    another:
        jiraRestUrl: https://something.atlassian.net
        jiraToken: $TOKEN_HERE
        jiraUsername: your@email.com
        jiraTokenType: personal token
```

I have a plan to add a note about config structure to the README.md.
